#!/usr/bin/env python3
"""Build the BB unsourced-grey list + migration + rollback from Quinn's per-number file (quinn-per-number-499.csv).
Usage: python3 gen_bb_unsourced_grey.py <quinn-per-number-499.csv>   (run from this folder; stdlib only)
Outputs (next to this script's repo paths):
  bb-unsourced-grey-list.csv                         machine-readable list, all 499 numbers, action grey|keep
  ../../../supabase/migrations/20261004010000_bb_unsourced_grey.sql            (table + data + patched recompute_user_eligibility)
  ../../../supabase/migrations/20261004010000_bb_unsourced_grey.rollback.sql.txt (restores the 20261003020000 function, drops the table)
Rule: Quinn number_level_verdict UNSOURCED -> source_status 'unsourced' (grey)
      CONTRADICTS -> 'contradicted' (grey; Quinn gives only published PEAKS, not a sourced minimum, so no number is corrected)
      SUPPORTS / PARTIAL/NOT COMPARABLE -> keep (not marked)
"""
import csv, sys, os
JOINT_KEY = {"Hip Flexion": "hip_flex", "Shoulder Flexion": "shoulder_flex", "Lumbar Flexion": "lumbar_flex",
             "Shoulder ER": "shoulder_er", "Ankle DF": "ankle_df", "Lumbar Extension": "lumbar_ext"}
STATUS = {"UNSOURCED": "unsourced", "CONTRADICTS": "contradicted"}
here = os.path.dirname(os.path.abspath(__file__))
rows = list(csv.DictReader(open(sys.argv[1], newline="", encoding="utf-8")))
assert len(rows) == 499, len(rows)
def num(v):
    f = float(v); return str(int(f)) if f == int(f) else repr(f)
out = []
for r in sorted(rows, key=lambda r: (r["technique_code"], JOINT_KEY[r["joint"]])):
    v = r["number_level_verdict"]
    st = STATUS.get(v)
    out.append({"sport": "bodybuilding", "technique_code": r["technique_code"], "exercise_name": r["exercise_name"],
                "family": r["family"], "joint": r["joint"], "joint_key": JOINT_KEY[r["joint"]], "tier": r["tier"],
                "app_value": num(r["app_value"]), "quinn_verdict": v, "source_status": st or "",
                "action": "grey" if st else "keep", "published_comparator": r["published_comparator"],
                "paper_ids": r["paper_ids"]})
with open(os.path.join(here, "bb-unsourced-grey-list.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(out[0].keys()), lineterminator="\n"); w.writeheader(); w.writerows(out)
g = [o for o in out if o["action"] == "grey"]
n_un = sum(o["source_status"] == "unsourced" for o in g); n_co = sum(o["source_status"] == "contradicted" for o in g)
assert (n_un, n_co) == (442, 7), (n_un, n_co)
q = lambda s: "'" + s.replace("'", "''") + "'"
vals = ",\n".join(f"  ({q(o['technique_code'])},{q(o['joint_key'])},{q(o['tier'])},{o['app_value']},{q(o['source_status'])},{q(o['quinn_verdict'])})" for o in g)
mig = f"""-- DRAFT, NOT APPLIED. Branch draft/bb-unsourced-grey-20261004 (built on PR #74, branch color-server-draft). Jim has NOT decided.
-- Quinn's BB peer review (Oct 3): of 499 Bodybuilding ROM numbers, {n_un} have no published support (UNSOURCED) and {n_co} are
-- CONTRADICTED by published values (hip flexion, 100-115 deg). This marks those {n_un + n_co} numbers so the engine renders them GREY
-- "no reference range yet" (reason no_reference_range, the mechanism PR #74 added). The 57 numbers that match a paper
-- (15 SUPPORTS + 35 PARTIAL/NOT COMPARABLE = 50 kept; the 7 more that match a paper are the CONTRADICTS, greyed) keep their current behaviour. No number in techniques is changed.
--
-- Where the BB numbers live: rom_thresholds has NO bodybuilding rows. The 499 numbers are techniques.<joint>_min (274 BB techniques).
-- So the mark is a small side table keyed (sport, technique_code, joint) and tied to the number (app_value): the mark only applies
-- while techniques.<joint>_min still equals app_value, so if someone later sources or changes a number the grey drops by itself.
--
-- Apply ORDER: 1) 20261003010000 (GREY tier + status_reason), 2) 20261003020000 (shared SQL rule), 3) this file, then deploy
-- compute-tiers (this branch) and re-POST latest assessments. Rollback: 20261004010000_bb_unsourced_grey.rollback.sql.txt.
-- Idempotent: safe to run twice (CREATE IF NOT EXISTS, upsert, CREATE OR REPLACE).
-- List source: docs/color-rule-drafts/bb-unsourced-grey/bb-unsourced-grey-list.csv (generated by gen_bb_unsourced_grey.py).

CREATE TABLE IF NOT EXISTS public.rom_number_source_status (
  sport         text        NOT NULL,
  technique_code text       NOT NULL,
  joint         text        NOT NULL,   -- app joint key: hip_flex | shoulder_flex | lumbar_flex | shoulder_er | ankle_df | lumbar_ext
  tier          text,                   -- beginner | intermediate | advanced (informational)
  app_value     numeric     NOT NULL,   -- the number being marked; the mark applies only while the live number equals this
  source_status text        NOT NULL CHECK (source_status IN ('unsourced', 'contradicted')),
  quinn_verdict text,
  marked_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (sport, technique_code, joint)
);
COMMENT ON TABLE public.rom_number_source_status IS 'ROM numbers with no published support (unsourced) or contradicted by published values. Engine renders them GREY, reason no_reference_range. Names/keys only, no personal data.';
ALTER TABLE public.rom_number_source_status ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rom_number_source_status_read ON public.rom_number_source_status;
CREATE POLICY rom_number_source_status_read ON public.rom_number_source_status FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL ON public.rom_number_source_status FROM anon, authenticated;
GRANT SELECT ON public.rom_number_source_status TO anon, authenticated;

-- Mark the {n_un + n_co} numbers. Only where the live technique number still equals Quinn's app_value (drift guard).
WITH q(technique_code, joint, tier, app_value, source_status, quinn_verdict) AS (VALUES
{vals}
), live AS (
  SELECT t.code AS technique_code, j.joint, j.val
    FROM public.techniques t
   CROSS JOIN LATERAL (VALUES ('hip_flex', t.hip_flex_min), ('shoulder_flex', t.shoulder_flex_min), ('lumbar_flex', t.lumbar_flex_min),
                              ('shoulder_er', t.shoulder_er_min), ('ankle_df', t.ankle_df_min), ('lumbar_ext', t.lumbar_ext_min)) AS j(joint, val)
   WHERE t.sport = 'bodybuilding'
)
INSERT INTO public.rom_number_source_status (sport, technique_code, joint, tier, app_value, source_status, quinn_verdict)
SELECT 'bodybuilding', q.technique_code, q.joint, q.tier, q.app_value, q.source_status, q.quinn_verdict
  FROM q JOIN live l ON l.technique_code = q.technique_code AND l.joint = q.joint AND l.val = q.app_value
ON CONFLICT (sport, technique_code, joint) DO UPDATE
  SET tier = EXCLUDED.tier, app_value = EXCLUDED.app_value, source_status = EXCLUDED.source_status, quinn_verdict = EXCLUDED.quinn_verdict;

DO $$
DECLARE n_un int; n_co int;
BEGIN
  SELECT count(*) FILTER (WHERE source_status = 'unsourced'), count(*) FILTER (WHERE source_status = 'contradicted')
    INTO n_un, n_co FROM public.rom_number_source_status WHERE sport = 'bodybuilding';
  IF n_un <> {n_un} OR n_co <> {n_co} THEN
    RAISE WARNING 'bb unsourced grey: expected {n_un} unsourced + {n_co} contradicted, found % + % (a techniques number changed since Quinn''s file, or marks were added by hand)', n_un, n_co;
  END IF;
END $$;
"""
print("list rows", len(out), "grey", len(g), "unsourced", n_un, "contradicted", n_co)

# ---- recompute_user_eligibility: copy of the PR #74 definition (20261003020000) + the unsourced join ----
mdir = os.path.normpath(os.path.join(here, "..", "..", "..", "supabase", "migrations"))
base = open(os.path.join(mdir, "20261003020000_recompute_user_eligibility_shared_rule.sql"), encoding="utf-8").read()
start = base.index("CREATE OR REPLACE FUNCTION public.recompute_user_eligibility")
fn = base[start:]
def rep(old, new):
    global fn
    assert fn.count(old) == 1, old
    fn = fn.replace(old, new)
rep("  c_hip_er_no_ref_min constant numeric := 50;\n",
    "  c_hip_er_no_ref_min constant numeric := 50;\n"
    "  -- BB UNSOURCED GREY (draft/bb-unsourced-grey-20261004; mirrors UNSOURCED_GREY_SWITCH / UNSOURCED_MARK_BEATS_SLR_OVERRIDE in rule.ts).\n"
    "  -- A requirement whose number is marked in rom_number_source_status (Quinn: no published support / contradicted) is GREY, reason\n"
    "  -- no_reference_range. Hip flexion on a move keeps the Base straight-leg color unless c_unsourced_beats_slr (PENDING JIM, default false).\n"
    "  c_unsourced_grey constant boolean := true;\n"
    "  c_unsourced_beats_slr constant boolean := false;\n")
rep("""               WHEN r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr
                 THEN""", """               WHEN r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT (mk.joint IS NOT NULL AND c_unsourced_beats_slr)
                 THEN""")
rep("""               WHEN r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min THEN 'GREY'   -- Legal: no reference range yet
""", """               WHEN r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min THEN 'GREY'   -- Legal: no reference range yet
               WHEN mk.joint IS NOT NULL THEN 'GREY'                                                           -- Quinn: unsourced / contradicted number
""")
rep("(r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr) AS slr_basis,",
    "(r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT (mk.joint IS NOT NULL AND c_unsourced_beats_slr)) AS slr_basis,")
rep("(r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min) AS no_ref\n",
    "(r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min)\n"
    "             OR (mk.joint IS NOT NULL AND NOT (r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT c_unsourced_beats_slr)) AS no_ref\n")
rep("        LEFT JOIN jv ON jv.joint = r.joint\n",
    "        LEFT JOIN jv ON jv.joint = r.joint\n"
    "        LEFT JOIN public.rom_number_source_status mk\n"
    "               ON c_unsourced_grey AND mk.sport = v_sport AND mk.technique_code = r.technique_code AND mk.joint = r.joint AND mk.app_value = r.req\n")
mig_full = mig + "\n-- recompute_user_eligibility = the PR #74 definition (20261003020000) plus the unsourced join (changes marked 'BB UNSOURCED GREY' / mk.).\n" + fn
open(os.path.join(mdir, "20261004010000_bb_unsourced_grey.sql"), "w", encoding="utf-8").write(mig_full)
rb = ("-- ROLLBACK for 20261004010000_bb_unsourced_grey.sql. DRAFT, NOT APPLIED. Restores recompute_user_eligibility to the PR #74\n"
      "-- definition (20261003020000), then drops the side table. After running: re-POST the latest assessments (or call\n"
      "-- recompute_user_eligibility per user) so technique_eligibility rows return to their previous colors.\n"
      "-- Run this BEFORE dropping the table (the function in this migration reads it).\n\n"
      + base[start:] + "\nDROP TABLE IF EXISTS public.rom_number_source_status;\n")
open(os.path.join(mdir, "20261004010000_bb_unsourced_grey.rollback.sql.txt"), "w", encoding="utf-8").write(rb)
print("migration + rollback written")
