#!/usr/bin/env python3
"""Generate the DRAFT matrix-load SQL (Quinn's 397 numbers -> techniques.<joint>_min) + dry-run query + rollback.
Reads /workspace/quinn-research/missing-397-map-20261003.csv. Writes files next to this script. Nothing is executed."""
import csv, os, collections
SRC = "/workspace/quinn-research/missing-397-map-20261003.csv"
OUT = os.path.dirname(os.path.abspath(__file__))
rows = list(csv.DictReader(open(SRC)))
tuples = []
for r in rows:
    col = r["missing_db_column"].split(".")[1]
    tuples.append((r["technique_id"], col, float(r["matrix_min"])))
assert len(tuples) == 397 and len({(t[0], t[1]) for t in tuples}) == 397
cols = sorted({t[1] for t in tuples})
def values(ts):
    return ",\n    ".join("('%s','%s',%s)" % (a, b, ("%g" % c)) for a, b, c in ts)
# Phase A: everything except hip flexion (hip flexion waits for the straight-leg color + shared-rule migration)
A = [t for t in tuples if t[1] != "hip_flex_min"]
B = [t for t in tuples if t[1] == "hip_flex_min"]
def update_sql(ts, label):
    # one UPDATE per column (column name cannot be a bind parameter); fills ONLY NULL cells, never overwrites
    out = []
    for col in sorted({t[1] for t in ts}):
        sub = [t for t in ts if t[1] == col]
        out.append(f"""-- {label}: {col} ({len(sub)} rows)
UPDATE public.techniques t SET {col} = v.val
  FROM (VALUES
    {values(sub)}
  ) AS v(code, col, val)
 WHERE t.code = v.code AND t.sport = 'bjj' AND t.{col} IS NULL;
""")
    return "\n".join(out)
hdr = """-- DRAFT, NOT APPLIED. Decision #9 (Jim): load Quinn's 397 missing matrix numbers into public.techniques.<joint>_min.
-- Source: /workspace/quinn-research/missing-397-map-20261003.csv (397 rows, 120 BJJ techniques, 10 joints). Generated by gen_matrix_load.py.
-- Fills ONLY cells that are NULL today (never overwrites). The two known differences (BT3/BT7 cervical lateral 25 vs 40) are NOT in the 397.
-- ORDER (Jim: after hip + ankle):
--   1) migration 20261003010000 (GREY tier), 2) compute-tiers v43 deployed, 3) migration 20261003020000 (shared SQL rule),
--   4) PHASE A below, 5) PHASE B (hip flexion) last. Until step 3, the LIVE recompute_user_eligibility compares these numbers raw
--   (ratio 0.90), and 87 hip-flexion numbers of 100+ against a straight-leg raise would turn most users RED. Do not run B early.
-- Notes: hip_ext_min (26) is not read by compute-tiers or the SQL fn (no Base hip extension test) so those stay GREY after the load.
--        cervical_rot_min (30): Base has no rotation test, so those moves stay GREY (incomplete).
--        Ankle: all 54 ankle numbers are already loaded (degree-style); they are NEVER compared to the cm reading (GREY).
--        3 tier notes quote ROMBOK: strip before any external use (not touched here).
BEGIN;
"""
open(f"{OUT}/matrix_load_397.sql", "w").write(
    hdr + "\n-- ===== PHASE A: %d numbers (all joints except hip flexion) =====\n" % len(A) + update_sql(A, "A") +
    "\n-- ===== PHASE B: %d numbers (hip flexion; run LAST) =====\n" % len(B) + update_sql(B, "B") + "\nCOMMIT;\n")
# rollback: null the cells ONLY where they still equal the loaded number (they were all NULL before the load)
rb = ["-- ROLLBACK for matrix_load_397.sql (DRAFT, not applied). All 397 cells were NULL before the load (checked read-only 2026-10-03).",
      "-- Sets a cell back to NULL only if it still holds the loaded number, so later hand edits are not erased.", "BEGIN;"]
for col in cols:
    sub = [t for t in tuples if t[1] == col]
    rb.append(f"""UPDATE public.techniques t SET {col} = NULL
  FROM (VALUES
    {values(sub)}
  ) AS v(code, col, val)
 WHERE t.code = v.code AND t.sport = 'bjj' AND t.{col} = v.val;
""")
rb.append("COMMIT;")
open(f"{OUT}/matrix_load_397.rollback.sql", "w").write("\n".join(rb) + "\n")
# dry-run (READ ONLY SELECT): current cell vs loaded value
cases = ",\n    ".join("('%s','%s',%s)" % t for t in tuples)
open(f"{OUT}/matrix_load_397.dryrun.sql", "w").write(f"""-- READ-ONLY dry run: what the load would change. status: fill (cell NULL, will be set), same (already equal), DIFFERS (cell has another number: NOT overwritten), no_technique (code not found)
WITH v(code, col, val) AS (VALUES
    {cases}
), cur AS (
  SELECT v.code, v.col, v.val, (to_jsonb(t) ->> v.col)::numeric AS cur_val, t.id IS NOT NULL AS found
    FROM v LEFT JOIN public.techniques t ON t.code = v.code AND t.sport = 'bjj'
)
SELECT CASE WHEN NOT found THEN 'no_technique' WHEN cur_val IS NULL THEN 'fill' WHEN cur_val = val THEN 'same' ELSE 'DIFFERS' END AS status,
       count(*) AS n,
       string_agg(CASE WHEN found AND cur_val IS NOT NULL AND cur_val <> val THEN code||'.'||col||' db='||cur_val||' new='||val END, '; ') AS differs_detail
  FROM cur GROUP BY 1 ORDER BY 1;
""")
print("A", len(A), "B", len(B), "cols", cols)
