-- DRAFT, NOT APPLIED. Branch draft/bb-unsourced-grey-20261004 (built on PR #74, branch color-server-draft). Jim has NOT decided.
-- Quinn's BB peer review (Oct 3): of 499 Bodybuilding ROM numbers, 442 have no published support (UNSOURCED) and 7 are
-- CONTRADICTED by published values (hip flexion, 100-115 deg). This marks those 449 numbers so the engine renders them GREY
-- "no reference range yet" (reason no_reference_range, the mechanism PR #74 added). The 57 numbers that match a paper
-- (15 SUPPORTS + 35 PARTIAL/NOT COMPARABLE = 50 kept; the 7 more that match a paper are the CONTRADICTS, greyed) keep their current behaviour. No number in techniques is changed.
--
-- Where the BB numbers live: rom_thresholds has NO bodybuilding rows. The 499 numbers are techniques.<joint>_min (274 BB techniques).
-- So the mark is a small side table keyed (sport, technique_code, joint) and tied to the number (app_value): the mark only applies
-- while techniques.<joint>_min still equals app_value, so if someone later sources or changes a number the grey drops by itself.
--
-- Apply ORDER: 1) 20261003010000 (GREY tier + status_reason), 2) 20261003020000 (shared SQL rule), 3) this file, then deploy
-- compute-tiers (this branch) and re-POST latest assessments. Rollback: 20261004010000_bb_unsourced_grey.rollback.sql.txt.
-- Idempotent: safe to run twice (CREATE IF NOT EXISTS, upsert, CREATE OR REPLACE).
-- List source: docs/color-rule-drafts/bb-unsourced-grey/bb-unsourced-grey-list.csv (generated by gen_bb_unsourced_grey.py).

CREATE TABLE IF NOT EXISTS public.rom_number_source_status (
  sport         text        NOT NULL,
  technique_code text       NOT NULL,
  joint         text        NOT NULL,   -- app joint key: hip_flex | shoulder_flex | lumbar_flex | shoulder_er | ankle_df | lumbar_ext
  tier          text,                   -- beginner | intermediate | advanced (informational)
  app_value     numeric     NOT NULL,   -- the number being marked; the mark applies only while the live number equals this
  source_status text        NOT NULL CHECK (source_status IN ('unsourced', 'contradicted')),
  quinn_verdict text,
  marked_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (sport, technique_code, joint)
);
COMMENT ON TABLE public.rom_number_source_status IS 'ROM numbers with no published support (unsourced) or contradicted by published values. Engine renders them GREY, reason no_reference_range. Names/keys only, no personal data.';
ALTER TABLE public.rom_number_source_status ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rom_number_source_status_read ON public.rom_number_source_status;
CREATE POLICY rom_number_source_status_read ON public.rom_number_source_status FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL ON public.rom_number_source_status FROM anon, authenticated;
GRANT SELECT ON public.rom_number_source_status TO anon, authenticated;

-- Mark the 449 numbers. Only where the live technique number still equals Quinn's app_value (drift guard).
WITH q(technique_code, joint, tier, app_value, source_status, quinn_verdict) AS (VALUES
  ('bb_back_barbell_bent_over_row_overhand_028','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_barbell_bent_over_row_overhand_028','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_barbell_bent_over_row_underhand_supinated_029','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_barbell_bent_over_row_underhand_supinated_029','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_cable_pullover_kneeling_or_standing_047','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_cable_pullover_kneeling_or_standing_047','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_cable_pullover_kneeling_or_standing_047','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_cable_single_arm_row_kneeling_or_half_kneeling_045','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_cable_single_arm_row_kneeling_or_half_kneeling_045','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_chest_supported_row_034','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_chest_supported_row_034','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_chest_supported_row_034','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_pullover_back_focus_036','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_pullover_back_focus_036','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_pullover_back_focus_036','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_romanian_deadlift_038','hip_flex','intermediate',105,'contradicted','CONTRADICTS'),
  ('bb_back_dumbbell_romanian_deadlift_038','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_romanian_deadlift_038','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_shrug_037','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_shrug_037','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_back_dumbbell_shrug_037','shoulder_flex','advanced',155,'unsourced','UNSOURCED'),
  ('bb_back_face_pull_cable_rope_046','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_face_pull_cable_rope_046','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_face_pull_cable_rope_046','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_incline_dumbbell_row_prone_035','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_incline_dumbbell_row_prone_035','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_incline_dumbbell_row_prone_035','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_close_grip_neutral_043','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_close_grip_neutral_043','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_close_grip_neutral_043','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_wide_overhand_to_chest_042','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_wide_overhand_to_chest_042','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_lat_pulldown_wide_overhand_to_chest_042','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_low_row_machine_angled_cable_or_plate_054','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_low_row_machine_angled_cable_or_plate_054','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_low_row_machine_angled_cable_or_plate_054','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_machine_chest_supported_row_048','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_machine_chest_supported_row_048','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_machine_chest_supported_row_048','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_machine_lat_pulldown_plate_loaded_or_selectorize_049','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_machine_lat_pulldown_plate_loaded_or_selectorize_049','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_machine_lat_pulldown_plate_loaded_or_selectorize_049','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_machine_row_hammer_strength_plate_loaded_050','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_machine_row_hammer_strength_plate_loaded_050','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_machine_row_hammer_strength_plate_loaded_050','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_machine_shrug_plate_loaded_or_smith_052','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_machine_shrug_plate_loaded_or_smith_052','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_machine_shrug_plate_loaded_or_smith_052','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_pendlay_row_030','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_pendlay_row_030','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_pendlay_row_030','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_rack_pull_below_knee_032','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_back_rack_pull_below_knee_032','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_back_rack_pull_below_knee_032','shoulder_flex','advanced',155,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_close_grip_v_bar_039','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_close_grip_v_bar_039','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_close_grip_v_bar_039','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_wide_grip_040','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_wide_grip_040','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_seated_cable_row_wide_grip_040','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_seated_lat_pulldown_machine_converging_arms_053','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_seated_lat_pulldown_machine_converging_arms_053','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_seated_lat_pulldown_machine_converging_arms_053','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_seated_row_machine_cable_or_cam_051','hip_flex','beginner',90,'unsourced','UNSOURCED'),
  ('bb_back_seated_row_machine_cable_or_cam_051','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_back_seated_row_machine_cable_or_cam_051','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_back_single_arm_dumbbell_row_bench_supported_033','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_single_arm_dumbbell_row_bench_supported_033','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_single_arm_dumbbell_row_bench_supported_033','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_standing_cable_row_low_cable_row_041','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_standing_cable_row_low_cable_row_041','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_standing_cable_row_low_cable_row_041','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_straight_arm_cable_pulldown_044','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_straight_arm_cable_pulldown_044','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_straight_arm_cable_pulldown_044','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_back_t_bar_row_landmine_031','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_back_t_bar_row_landmine_031','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_back_t_bar_row_landmine_031','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_biceps_barbell_curl_standard_055','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_bayesian_cable_curl_face_away_low_pulley_069','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_cable_preacher_curl_low_pulley_pad_073','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_chin_up_supinated_grip_079','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_close_grip_barbell_curl_057','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_concentration_curl_065','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_cross_body_cable_curl_low_pulley_075','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_drag_curl_barbell_058','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_dumbbell_zottman_curl_066','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_ez_bar_curl_056','shoulder_er','beginner',50,'unsourced','UNSOURCED'),
  ('bb_biceps_hammer_curl_dumbbell_063','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_high_cable_curl_overhead_cable_curl_071','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_incline_dumbbell_curl_45_60_061','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_inverse_zottman_hammer_concentric_supinated_ecce_067','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_lying_flat_bench_db_curl_062','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_machine_curl_cam_based_077','shoulder_er','beginner',50,'unsourced','UNSOURCED'),
  ('bb_biceps_machine_preacher_curl_076','shoulder_er','beginner',50,'unsourced','UNSOURCED'),
  ('bb_biceps_preacher_curl_dumbbell_064','shoulder_er','beginner',50,'unsourced','UNSOURCED'),
  ('bb_biceps_preacher_hammer_curl_db_068','shoulder_er','beginner',50,'unsourced','UNSOURCED'),
  ('bb_biceps_resistance_band_curl_080','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_reverse_curl_barbell_059','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_rope_hammer_curl_cable_low_pulley_074','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_scott_curl_machine_barbell_on_vertical_pad_078','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_biceps_single_arm_cable_curl_low_pulley_supinated_072','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_standard_cable_curl_low_pulley_facing_070','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_standing_dumbbell_curl_060','shoulder_er','intermediate',65,'unsourced','UNSOURCED'),
  ('bb_biceps_trx_ring_curl_081','shoulder_er','advanced',75,'unsourced','UNSOURCED'),
  ('bb_calves_barbell_donkey_calf_raise_weighted_bent_over_090','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_barbell_standing_calf_raise_on_step_088','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_bilateral_bodyweight_calf_raise_on_step_100','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_bilateral_dumbbell_standing_calf_raise_on_step_092','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_bodyweight_donkey_calf_raise_bent_over_two_leg_098','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_cable_seated_calf_raise_ankle_attachment_096','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_cable_standing_calf_raise_ankle_attachment_step_095','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_donkey_calf_raise_machine_084','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_dumbbell_donkey_calf_raise_single_leg_bent_over_094','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_jump_rope_skipping_101','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_leg_press_toe_press_standing_rom_knee_straight_085','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_resistance_band_calf_raise_on_step_097','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_seated_barbell_calf_raise_knee_bent_on_step_089','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_seated_calf_raise_machine_knee_bent_083','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_seated_dumbbell_calf_raise_knee_bent_093','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_single_leg_bodyweight_calf_raise_on_step_099','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_single_leg_dumbbell_calf_raise_on_step_091','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_calves_smith_machine_calf_raise_on_step_086','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_standing_calf_raise_machine_082','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_calves_tibialis_machine_anterior_tibialis_087','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_calves_wall_calf_stretch_loaded_eccentric_hold_102','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_chest_assisted_dip_machine_chest_focus_128','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_assisted_dip_machine_chest_focus_128','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_banded_push_up_133','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_banded_push_up_133','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_barbell_floor_press_107','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_barbell_floor_press_107','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_cable_crossover_cross_body_119','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_cable_crossover_cross_body_119','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_cable_fly_single_arm_121','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_cable_fly_single_arm_121','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_cable_press_around_machine_127','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_cable_press_around_machine_127','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_cable_press_flat_standing_120','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_cable_press_flat_standing_120','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_chest_dip_forward_lean_132','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_chest_dip_forward_lean_132','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_decline_barbell_bench_press_105','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_decline_barbell_bench_press_105','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_decline_dumbbell_fly_112','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_decline_dumbbell_fly_112','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_deficit_push_up_130','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_deficit_push_up_130','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_dumbbell_guillotine_press_114','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_dumbbell_guillotine_press_114','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_dumbbell_pullover_113','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_dumbbell_pullover_113','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_flat_barbell_bench_press_103','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_flat_dumbbell_bench_press_108','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_flat_dumbbell_bench_press_108','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_flat_dumbbell_fly_110','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_flat_dumbbell_fly_110','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_high_to_low_cable_fly_117','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_high_to_low_cable_fly_117','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_incline_barbell_bench_press_104','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_incline_barbell_bench_press_104','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_incline_dumbbell_bench_press_109','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_incline_dumbbell_bench_press_109','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_incline_dumbbell_fly_111','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_incline_dumbbell_fly_111','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_incline_machine_chest_press_124','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_incline_machine_chest_press_124','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_low_to_high_cable_fly_116','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_low_to_high_cable_fly_116','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_machine_chest_press_converging_122','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_machine_chest_press_converging_122','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_pec_deck_machine_fly_123','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_pec_deck_machine_fly_123','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_seated_cable_fly_incline_bench_118','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_seated_cable_fly_incline_bench_118','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_smith_machine_bench_press_flat_125','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_smith_machine_bench_press_flat_125','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_smith_machine_incline_press_126','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_chest_smith_machine_incline_press_126','shoulder_flex','beginner',100,'unsourced','UNSOURCED'),
  ('bb_chest_standard_push_up_129','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_standard_push_up_129','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_standing_cable_fly_mid_cable_115','shoulder_er','intermediate',75,'unsourced','UNSOURCED'),
  ('bb_chest_standing_cable_fly_mid_cable_115','shoulder_flex','intermediate',130,'unsourced','UNSOURCED'),
  ('bb_chest_weighted_push_up_131','shoulder_er','advanced',85,'unsourced','UNSOURCED'),
  ('bb_chest_weighted_push_up_131','shoulder_flex','advanced',150,'unsourced','UNSOURCED'),
  ('bb_chest_wide_grip_flat_barbell_press_106','shoulder_er','beginner',60,'unsourced','UNSOURCED'),
  ('bb_core_ab_crunch_machine_cam_based_225','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_ab_crunch_machine_cam_based_225','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_ab_crunch_machine_cam_based_225','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_ab_wheel_rollout_240','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_ab_wheel_rollout_240','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_ab_wheel_rollout_240','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_barbell_rollout_ab_wheel_equivalent_230','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_barbell_rollout_ab_wheel_equivalent_230','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_barbell_rollout_ab_wheel_equivalent_230','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_belt_squat_machine_hip_flexion_standing_229','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_belt_squat_machine_hip_flexion_standing_229','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_belt_squat_machine_hip_flexion_standing_229','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_bicycle_crunch_241','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_bicycle_crunch_241','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_bicycle_crunch_241','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_kneeling_rope_217','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_kneeling_rope_217','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_kneeling_rope_217','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_seated_bench_218','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_seated_bench_218','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_cable_crunch_seated_bench_218','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_cable_hip_flexion_lying_ankle_attachment_224','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_cable_hip_flexion_lying_ankle_attachment_224','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_cable_hip_flexion_lying_ankle_attachment_224','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_cable_pallof_press_222','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_cable_pallof_press_222','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_cable_pallof_press_222','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_high_to_low_220','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_high_to_low_220','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_high_to_low_220','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_low_to_high_221','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_low_to_high_221','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_cable_woodchop_low_to_high_221','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_captain_s_chair_leg_raise_227','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_captain_s_chair_leg_raise_227','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_decline_bench_ab_machine_decline_sit_up_226','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_decline_bench_ab_machine_decline_sit_up_226','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_decline_bench_ab_machine_decline_sit_up_226','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_dragon_flag_243','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_dragon_flag_243','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_dragon_flag_243','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_rollout_db_on_floor_236','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_rollout_db_on_floor_236','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_rollout_db_on_floor_236','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_russian_twist_weighted_235','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_russian_twist_weighted_235','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_russian_twist_weighted_235','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_side_bend_234','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_side_bend_234','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_side_bend_234','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_woodchop_single_db_both_hands_237','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_woodchop_single_db_both_hands_237','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_dumbbell_woodchop_single_db_both_hands_237','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_good_morning_spinal_flexion_variation_light_load_232','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_hanging_knee_raise_239','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_hanging_knee_raise_239','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_hanging_leg_raise_straight_leg_238','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_hanging_leg_raise_straight_leg_238','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_hollow_body_hold_rock_244','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_hollow_body_hold_rock_244','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_hollow_body_hold_rock_244','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_l_sit_parallel_bars_floor_245','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_l_sit_parallel_bars_floor_245','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_l_sit_parallel_bars_floor_245','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_oblique_cable_crunch_kneeling_219','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_oblique_cable_crunch_kneeling_219','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_oblique_cable_crunch_kneeling_219','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_roman_chair_sit_up_hyperextension_bench_228','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_roman_chair_sit_up_hyperextension_bench_228','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_roman_chair_sit_up_hyperextension_bench_228','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_standing_cable_crunch_rope_bent_over_223','hip_flex','intermediate',105,'unsourced','UNSOURCED'),
  ('bb_core_standing_cable_crunch_rope_bent_over_223','lumbar_ext','intermediate',18,'unsourced','UNSOURCED'),
  ('bb_core_standing_cable_crunch_rope_bent_over_223','lumbar_flex','intermediate',45,'unsourced','UNSOURCED'),
  ('bb_core_v_up_242','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_v_up_242','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_v_up_242','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_core_weighted_crunch_db_or_plate_on_chest_233','hip_flex','advanced',120,'unsourced','UNSOURCED'),
  ('bb_core_weighted_crunch_db_or_plate_on_chest_233','lumbar_ext','advanced',22,'unsourced','UNSOURCED'),
  ('bb_core_weighted_crunch_db_or_plate_on_chest_233','lumbar_flex','advanced',55,'unsourced','UNSOURCED'),
  ('bb_core_weighted_decline_sit_up_barbell_plate_231','hip_flex','beginner',85,'unsourced','UNSOURCED'),
  ('bb_core_weighted_decline_sit_up_barbell_plate_231','lumbar_ext','beginner',15,'unsourced','UNSOURCED'),
  ('bb_core_weighted_decline_sit_up_barbell_plate_231','lumbar_flex','beginner',35,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_barbell_good_morning_136','hip_flex','intermediate',100,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_barbell_hip_thrust_137','hip_flex','advanced',115,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_bodyweight_bulgarian_split_squat_161','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_hip_abduction_glute_med_148','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_hip_abduction_glute_med_148','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_kickback_hip_extension_146','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_kickback_hip_extension_146','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_pull_through_hip_hinge_147','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_pull_through_hip_hinge_147','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_rdl_low_pulley_149','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_rdl_low_pulley_149','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_standing_hip_extension_glute_focused_150','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_cable_standing_hip_extension_glute_focused_150','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_donkey_kick_hip_extension_162','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_donkey_kick_hip_extension_162','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_bulgarian_split_squat_glute_focus_143','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_hip_thrust_single_leg_or_bilateral_142','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_hip_thrust_single_leg_or_bilateral_142','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_rdl_romanian_deadlift_140','hip_flex','intermediate',100,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_dumbbell_rdl_romanian_deadlift_140','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_single_leg_rdl_141','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_single_leg_rdl_141','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_step_up_glute_focus_145','hip_flex','intermediate',100,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_step_up_glute_focus_145','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_dumbbell_walking_lunge_144','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_ghd_hamstring_curl_glute_ham_raise_157','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_ghd_hip_extension_glute_ham_developer_156','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_glute_bridge_bodyweight_160','hip_flex','advanced',115,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_glute_bridge_bodyweight_160','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_machine_hip_abduction_154','hip_flex','beginner',80,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_machine_hip_abduction_154','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_machine_hip_thrust_glute_drive_nautilus_153','hip_flex','beginner',80,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_machine_hip_thrust_glute_drive_nautilus_153','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_nordic_hamstring_curl_159','hip_flex','intermediate',100,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_nordic_hamstring_curl_159','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_prone_leg_curl_hip_extended_152','hip_flex','advanced',115,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_prone_leg_curl_hip_extended_152','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_romanian_deadlift_rdl_134','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_seated_leg_curl_hip_flexed_151','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_smith_machine_lunge_front_foot_elevated_158','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_stiff_leg_deadlift_sldl_135','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_hamstrings_glutes_sumo_deadlift_139','hip_flex','advanced',115,'contradicted','CONTRADICTS'),
  ('bb_hamstrings_glutes_sumo_deadlift_139','lumbar_flex','advanced',50,'unsourced','UNSOURCED'),
  ('bb_quads_barbell_lunge_walking_stationary_005','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_belt_squat_cable_or_machine_019','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_belt_squat_cable_or_machine_019','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_belt_squat_cable_or_machine_019','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_cable_leg_extension_ankle_attachment_012','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_cable_leg_extension_ankle_attachment_012','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_cable_leg_extension_ankle_attachment_012','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_cable_pull_through_squat_variation_013','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_quads_cable_pull_through_squat_variation_013','hip_flex','advanced',125,'unsourced','UNSOURCED'),
  ('bb_quads_cable_pull_through_squat_variation_013','lumbar_flex','advanced',45,'unsourced','UNSOURCED'),
  ('bb_quads_cable_squat_low_cable_belt_or_handle_011','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_cable_squat_low_cable_belt_or_handle_011','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_cable_squat_low_cable_belt_or_handle_011','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_bulgarian_split_squat_rfess_007','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_lunge_stationary_009','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_sissy_squat_assisted_010','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_sissy_squat_assisted_010','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_sissy_squat_assisted_010','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_step_up_008','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_step_up_008','hip_flex','advanced',125,'unsourced','UNSOURCED'),
  ('bb_quads_dumbbell_step_up_008','lumbar_flex','advanced',45,'unsourced','UNSOURCED'),
  ('bb_quads_front_squat_003','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_front_squat_003','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_goblet_squat_006','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_goblet_squat_006','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_goblet_squat_006','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_hack_squat_machine_015','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_hack_squat_machine_015','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_hack_squat_machine_015','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_jump_squat_027','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_quads_jump_squat_027','hip_flex','advanced',125,'unsourced','UNSOURCED'),
  ('bb_quads_jump_squat_027','lumbar_flex','advanced',45,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_45_sled_016','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_45_sled_016','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_45_sled_016','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_low_foot_close_stance_quad_focus_021','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_low_foot_close_stance_quad_focus_021','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_leg_press_low_foot_close_stance_quad_focus_021','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_machine_leg_press_single_leg_022','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_machine_leg_press_single_leg_022','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_machine_leg_press_single_leg_022','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_pendulum_squat_018','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_pendulum_squat_018','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_pendulum_squat_018','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_reverse_nordic_curl_024','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_reverse_nordic_curl_024','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_reverse_nordic_curl_024','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_seated_leg_extension_reclined_017','ankle_df','beginner',12,'unsourced','UNSOURCED'),
  ('bb_quads_seated_leg_extension_reclined_017','hip_flex','beginner',95,'unsourced','UNSOURCED'),
  ('bb_quads_seated_leg_extension_reclined_017','lumbar_flex','beginner',30,'unsourced','UNSOURCED'),
  ('bb_quads_single_leg_cable_squat_pistol_assisted_014','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_single_leg_cable_squat_pistol_assisted_014','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_single_leg_cable_squat_pistol_assisted_014','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_sissy_squat_bodyweight_025','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_sissy_squat_bodyweight_025','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_sissy_squat_bodyweight_025','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_quads_wall_sit_isometric_026','ankle_df','advanced',20,'unsourced','UNSOURCED'),
  ('bb_quads_wall_sit_isometric_026','hip_flex','advanced',125,'unsourced','UNSOURCED'),
  ('bb_quads_wall_sit_isometric_026','lumbar_flex','advanced',45,'unsourced','UNSOURCED'),
  ('bb_quads_zercher_squat_004','ankle_df','intermediate',16,'unsourced','UNSOURCED'),
  ('bb_quads_zercher_squat_004','hip_flex','intermediate',115,'unsourced','UNSOURCED'),
  ('bb_quads_zercher_squat_004','lumbar_flex','intermediate',40,'unsourced','UNSOURCED'),
  ('bb_shoulders_arnold_press_169','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_arnold_press_169','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_barbell_high_pull_hang_167','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_barbell_high_pull_hang_167','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_barbell_overhead_press_standing_163','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_barbell_upright_row_wide_grip_166','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_barbell_upright_row_wide_grip_166','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_behind_the_neck_barbell_press_165','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_face_pull_rope_180','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_face_pull_rope_180','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_front_raise_179','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_front_raise_179','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_lateral_raise_bilateral_crossover_177','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_lateral_raise_bilateral_crossover_177','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_rear_delt_pull_single_arm_high_pulley_182','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_rear_delt_pull_single_arm_high_pulley_182','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_upright_row_rope_181','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_cable_upright_row_rope_181','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_front_raise_175','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_front_raise_175','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_lateral_raise_standing_170','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_lateral_raise_standing_170','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_rear_delt_fly_bent_over_172','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_rear_delt_fly_bent_over_172','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_upright_row_174','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_dumbbell_upright_row_174','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_shoulders_incline_dumbbell_rear_delt_fly_173','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_incline_dumbbell_rear_delt_fly_173','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_landmine_press_single_arm_189','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_landmine_press_single_arm_189','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_lateral_raise_machine_187','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_lateral_raise_machine_187','shoulder_flex','beginner',130,'unsourced','UNSOURCED'),
  ('bb_shoulders_lean_away_cable_lateral_raise_183','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_lean_away_cable_lateral_raise_183','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_machine_shoulder_press_converging_plate_loaded_184','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_machine_shoulder_press_converging_plate_loaded_184','shoulder_flex','beginner',130,'unsourced','UNSOURCED'),
  ('bb_shoulders_pec_deck_rear_delt_reverse_grip_188','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_pec_deck_rear_delt_reverse_grip_188','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_reverse_cable_crossover_high_to_low_rear_delt_178','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_reverse_cable_crossover_high_to_low_rear_delt_178','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_reverse_pec_deck_machine_rear_delt_fly_185','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_reverse_pec_deck_machine_rear_delt_fly_185','shoulder_flex','beginner',130,'unsourced','UNSOURCED'),
  ('bb_shoulders_seated_barbell_overhead_press_164','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_seated_dumbbell_overhead_press_168','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_seated_dumbbell_overhead_press_168','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_seated_machine_rear_delt_row_wide_grip_190','shoulder_er','beginner',65,'unsourced','UNSOURCED'),
  ('bb_shoulders_seated_machine_rear_delt_row_wide_grip_190','shoulder_flex','beginner',130,'unsourced','UNSOURCED'),
  ('bb_shoulders_side_lying_dumbbell_lateral_raise_171','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_side_lying_dumbbell_lateral_raise_171','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_single_arm_cable_lateral_raise_arm_behind_body_176','shoulder_er','intermediate',80,'unsourced','UNSOURCED'),
  ('bb_shoulders_single_arm_cable_lateral_raise_arm_behind_body_176','shoulder_flex','intermediate',160,'unsourced','UNSOURCED'),
  ('bb_shoulders_smith_machine_overhead_press_186','shoulder_er','advanced',88,'unsourced','UNSOURCED'),
  ('bb_shoulders_smith_machine_overhead_press_186','shoulder_flex','advanced',175,'unsourced','UNSOURCED'),
  ('bb_triceps_barbell_overhead_triceps_extension_standing_seat_195','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_cable_bar_pushdown_pronated_grip_205','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_cable_kickback_elbow_at_side_207','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_cable_rope_pushdown_neutral_shoulder_204','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_diamond_push_up_214','shoulder_flex','advanced',165,'unsourced','UNSOURCED'),
  ('bb_triceps_dumbbell_kickback_200','shoulder_flex','advanced',165,'unsourced','UNSOURCED'),
  ('bb_triceps_dumbbell_overhead_triceps_extension_two_hand_197','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_dumbbell_skull_crusher_flat_bench_196','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_ez_bar_skull_crusher_decline_bench_193','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_ez_bar_skull_crusher_flat_bench_192','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_jm_press_194','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_katana_cable_triceps_extension_208','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_lying_dumbbell_triceps_extension_pullover_ext_199','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_machine_dip_assisted_or_weighted_211','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_machine_tricep_extension_overhead_shoulder_flexe_209','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_machine_tricep_pushdown_cam_210','shoulder_flex','beginner',110,'unsourced','UNSOURCED'),
  ('bb_triceps_overhead_cable_triceps_extension_rope_face_away_202','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_pike_push_up_decline_push_up_215','shoulder_flex','advanced',165,'unsourced','UNSOURCED'),
  ('bb_triceps_reverse_grip_cable_pushdown_supinated_206','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_single_arm_dumbbell_overhead_extension_198','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_single_arm_overhead_cable_extension_203','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_smith_machine_close_grip_bench_press_212','shoulder_flex','intermediate',140,'unsourced','UNSOURCED'),
  ('bb_triceps_tate_press_db_elbows_flared_201','shoulder_flex','advanced',165,'unsourced','UNSOURCED')
), live AS (
  SELECT t.code AS technique_code, j.joint, j.val
    FROM public.techniques t
   CROSS JOIN LATERAL (VALUES ('hip_flex', t.hip_flex_min), ('shoulder_flex', t.shoulder_flex_min), ('lumbar_flex', t.lumbar_flex_min),
                              ('shoulder_er', t.shoulder_er_min), ('ankle_df', t.ankle_df_min), ('lumbar_ext', t.lumbar_ext_min)) AS j(joint, val)
   WHERE t.sport = 'bodybuilding'
)
INSERT INTO public.rom_number_source_status (sport, technique_code, joint, tier, app_value, source_status, quinn_verdict)
SELECT 'bodybuilding', q.technique_code, q.joint, q.tier, q.app_value, q.source_status, q.quinn_verdict
  FROM q JOIN live l ON l.technique_code = q.technique_code AND l.joint = q.joint AND l.val = q.app_value
ON CONFLICT (sport, technique_code, joint) DO UPDATE
  SET tier = EXCLUDED.tier, app_value = EXCLUDED.app_value, source_status = EXCLUDED.source_status, quinn_verdict = EXCLUDED.quinn_verdict;

DO $$
DECLARE n_un int; n_co int;
BEGIN
  SELECT count(*) FILTER (WHERE source_status = 'unsourced'), count(*) FILTER (WHERE source_status = 'contradicted')
    INTO n_un, n_co FROM public.rom_number_source_status WHERE sport = 'bodybuilding';
  IF n_un <> 442 OR n_co <> 7 THEN
    RAISE WARNING 'bb unsourced grey: expected 442 unsourced + 7 contradicted, found % + % (a techniques number changed since Quinn''s file, or marks were added by hand)', n_un, n_co;
  END IF;
END $$;

-- recompute_user_eligibility = the PR #74 definition (20261003020000) plus the unsourced join (changes marked 'BB UNSOURCED GREY' / mk.).
CREATE OR REPLACE FUNCTION public.recompute_user_eligibility(p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  c_hip_flex_moves_use_slr constant boolean := true;   -- PENDING JIM (mirrors HIP_FLEX_MOVES_USE_SLR_COLOR)
  c_grey_beats_yellow constant boolean := true;        -- PENDING JIM (mirrors GREY_BEATS_YELLOW; RED always wins)
  c_one_side constant text := 'grey';                  -- PENDING JIM (mirrors ONE_SIDE_MISSING_POLICY: 'grey' | 'use_measured_side')
  -- LEGAL (Stacy, STACY-CLEARANCES section 10; mirrors NO_REFERENCE_RANGE_SWITCH / HIP_ER_NO_REFERENCE_MIN in rule.ts): a hip external
  -- rotation bar of c_hip_er_no_ref_min or more is far above the healthy average (about 36 degrees), so it stays GREY with reason
  -- no_reference_range until Quinn answers Q4 / Q5. The ankle degree-style path (unit_pending) uses the same reason.
  c_no_reference_range constant boolean := true;
  c_hip_er_no_ref_min constant numeric := 50;
  -- BB UNSOURCED GREY (draft/bb-unsourced-grey-20261004; mirrors UNSOURCED_GREY_SWITCH / UNSOURCED_MARK_BEATS_SLR_OVERRIDE in rule.ts).
  -- A requirement whose number is marked in rom_number_source_status (Quinn: no published support / contradicted) is GREY, reason
  -- no_reference_range. Hip flexion on a move keeps the Base straight-leg color unless c_unsourced_beats_slr (PENDING JIM, default false).
  c_unsourced_grey constant boolean := true;
  c_unsourced_beats_slr constant boolean := false;
  v_assessment   assessments%ROWTYPE;
  v_sports       text[];
  v_sport        text;
  v_now          timestamptz := now();
  v_result       jsonb := '{}'::jsonb;
  v_written      int;
  v_gender       text;
  v_dom          text;
BEGIN
  SELECT array_remove(COALESCE(sports_enabled, ARRAY['general']::text[]), 'general'), gender
    INTO v_sports, v_gender
    FROM users WHERE id = p_user_id;

  IF v_sports IS NULL OR array_length(v_sports, 1) IS NULL THEN
    RETURN jsonb_build_object('user_id', p_user_id, 'status', 'no_owned_sports');
  END IF;

  SELECT * INTO v_assessment
    FROM assessments
   WHERE user_id = p_user_id
   ORDER BY assessed_at DESC NULLS LAST, created_at DESC NULLS LAST
   LIMIT 1;

  IF v_assessment.id IS NULL THEN
    RETURN jsonb_build_object('user_id', p_user_id, 'status', 'no_assessment');
  END IF;

  BEGIN
    PERFORM public.compute_joint_scores(v_assessment.id);
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  -- Dominant side drives LEAD / HOOK / TRAIL. Unknown = worse side.
  SELECT lower(btrim(a.dominant_side)) INTO v_dom
    FROM athletes a
   WHERE (v_assessment.athlete_id IS NOT NULL AND a.id = v_assessment.athlete_id)
      OR (v_assessment.athlete_id IS NULL AND a.user_id = p_user_id)
   LIMIT 1;
  v_dom := CASE WHEN v_dom IN ('left', 'l') THEN 'left' WHEN v_dom IN ('right', 'r') THEN 'right' ELSE NULL END;

  FOREACH v_sport IN ARRAY v_sports LOOP
    IF v_sport NOT IN ('bjj', 'bodybuilding') THEN
      v_result := v_result || jsonb_build_object(v_sport, 'skipped_no_catalog');
      CONTINUE;
    END IF;

    WITH
    -- athlete values per joint, left / right (single-value joints use the same value twice)
    jv(joint, l, r) AS (
      VALUES
        ('hip_er',        public.rom_valid_reading(v_assessment.hip_er_l::numeric),        public.rom_valid_reading(v_assessment.hip_er_r::numeric)),
        ('hip_ir',        public.rom_valid_reading(v_assessment.hip_ir_l::numeric),        public.rom_valid_reading(v_assessment.hip_ir_r::numeric)),
        ('hip_abd',       public.rom_valid_reading(v_assessment.hip_abd_l::numeric),       public.rom_valid_reading(v_assessment.hip_abd_r::numeric)),
        ('hip_flex',      public.rom_valid_reading(v_assessment.hip_flex_l::numeric),      public.rom_valid_reading(v_assessment.hip_flex_r::numeric)),
        ('shoulder_er',   public.rom_valid_reading(v_assessment.shoulder_er_l::numeric),   public.rom_valid_reading(v_assessment.shoulder_er_r::numeric)),
        ('shoulder_flex', public.rom_valid_reading(v_assessment.shoulder_flex_l::numeric), public.rom_valid_reading(v_assessment.shoulder_flex_r::numeric)),
        ('ankle_df',      public.rom_valid_reading(v_assessment.ankle_df_l::numeric),      public.rom_valid_reading(v_assessment.ankle_df_r::numeric)),
        ('cervical_rot',  public.rom_valid_reading(v_assessment.cervical_rot_l::numeric),  public.rom_valid_reading(v_assessment.cervical_rot_r::numeric)),
        ('cervical_lat',  public.rom_valid_reading(v_assessment.cervical_lat_l::numeric),  public.rom_valid_reading(v_assessment.cervical_lat_r::numeric)),
        ('lumbar_flex',   public.rom_valid_reading(v_assessment.lumbar_flex::numeric),     public.rom_valid_reading(v_assessment.lumbar_flex::numeric)),
        ('lumbar_ext',    public.rom_valid_reading(v_assessment.lumbar_ext::numeric),      public.rom_valid_reading(v_assessment.lumbar_ext::numeric)),
        ('cervical_flex', public.rom_valid_reading(v_assessment.cervical_flex::numeric),   public.rom_valid_reading(v_assessment.cervical_flex::numeric)),
        ('cervical_ext',  public.rom_valid_reading(v_assessment.cervical_ext::numeric),    public.rom_valid_reading(v_assessment.cervical_ext::numeric))
    ),
    -- documented requirements (rom_thresholds). An explicit cm ankle row replaces a unit-less ankle row.
    mat0 AS (
      SELECT m.technique_code, public.rom_norm_joint(m.joint) AS j0, m.required_value::numeric AS req,
             upper(btrim(m.laterality_rule)) AS lat
        FROM rom_thresholds m
       WHERE m.sport = v_sport AND m.required_value IS NOT NULL AND m.required_value > 0
    ),
    mat1 AS (
      SELECT technique_code, CASE WHEN j0 = 'ankle_df_cm' THEN 'ankle_df' ELSE j0 END AS joint,
             (j0 = 'ankle_df_cm') AS is_cm, req, lat
        FROM mat0
    ),
    mat2 AS (
      SELECT * FROM mat1 x
       WHERE NOT (x.joint = 'ankle_df' AND NOT x.is_cm
                  AND EXISTS (SELECT 1 FROM mat1 y WHERE y.technique_code = x.technique_code AND y.joint = 'ankle_df' AND y.is_cm))
    ),
    -- two rows for one move + joint: the stricter (larger) number applies
    mat AS (
      SELECT DISTINCT ON (technique_code, joint) technique_code, joint, is_cm, req, lat
        FROM mat2
       ORDER BY technique_code, joint, req DESC, lat NULLS LAST
    ),
    -- legacy techniques.*_min fills only joints the matrix has no number for (kept, flagged undocumented)
    legacy AS (
      SELECT t.code AS technique_code, j.joint, false AS is_cm, j.thresh::numeric AS req, NULL::text AS lat
        FROM techniques t
       CROSS JOIN LATERAL (VALUES
          ('hip_er', t.hip_er_min), ('hip_ir', t.hip_ir_min), ('hip_abd', t.hip_abd_min), ('hip_flex', t.hip_flex_min),
          ('shoulder_er', t.shoulder_er_min), ('shoulder_flex', t.shoulder_flex_min), ('ankle_df', t.ankle_df_min),
          ('cervical_rot', t.cervical_rot_min), ('cervical_lat', t.cervical_lat_min), ('lumbar_flex', t.lumbar_flex_min),
          ('lumbar_ext', t.lumbar_ext_min), ('cervical_flex', t.cervical_flex_min), ('cervical_ext', t.cervical_ext_min)
       ) AS j(joint, thresh)
       WHERE t.sport = v_sport AND j.thresh IS NOT NULL AND j.thresh > 0
         AND NOT EXISTS (SELECT 1 FROM mat WHERE mat.technique_code = t.code AND mat.joint = j.joint)
    ),
    reqs AS (SELECT * FROM mat UNION ALL SELECT * FROM legacy),
    graded AS (
      SELECT r.technique_code, r.joint, r.req,
             v.val,
             CASE
               WHEN r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT (mk.joint IS NOT NULL AND c_unsourced_beats_slr)
                 THEN public.rom_pick_leg_status(public.rom_slr_leg(v_gender, jv.l), public.rom_slr_leg(v_gender, jv.r), r.lat, v_dom)
               WHEN r.joint = 'ankle_df' AND NOT r.is_cm THEN 'GREY'          -- F-17: cm reading never vs a unit-less requirement
               WHEN r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min THEN 'GREY'   -- Legal: no reference range yet
               WHEN mk.joint IS NOT NULL THEN 'GREY'                                                           -- Quinn: unsourced / contradicted number
               ELSE public.rom_classify_joint(v.val, r.req, r.joint)
             END AS status,
             (r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT (mk.joint IS NOT NULL AND c_unsourced_beats_slr)) AS slr_basis,
             (r.joint = 'ankle_df' AND NOT r.is_cm) AS unit_pending,
             (r.joint = 'hip_er' AND c_no_reference_range AND r.req >= c_hip_er_no_ref_min)
             OR (mk.joint IS NOT NULL AND NOT (r.joint = 'hip_flex' AND c_hip_flex_moves_use_slr AND NOT c_unsourced_beats_slr)) AS no_ref
        FROM reqs r
        LEFT JOIN jv ON jv.joint = r.joint
        LEFT JOIN public.rom_number_source_status mk
               ON c_unsourced_grey AND mk.sport = v_sport AND mk.technique_code = r.technique_code AND mk.joint = r.joint AND mk.app_value = r.req
        CROSS JOIN LATERAL (SELECT CASE
            WHEN jv.joint IS NULL OR (jv.l IS NULL AND jv.r IS NULL) THEN NULL
            WHEN r.lat IN ('LEAD', 'HOOK', 'TRAIL') AND v_dom IS NOT NULL THEN
              CASE WHEN c_one_side = 'grey' THEN CASE WHEN (v_dom = 'left') = (r.lat = 'LEAD') THEN jv.l ELSE jv.r END
                   ELSE COALESCE(CASE WHEN (v_dom = 'left') = (r.lat = 'LEAD') THEN jv.l ELSE jv.r END, LEAST(jv.l, jv.r)) END
            WHEN c_one_side = 'grey' AND (jv.l IS NULL OR jv.r IS NULL) THEN NULL
            WHEN r.lat = 'ANY' THEN GREATEST(jv.l, jv.r)
            ELSE LEAST(jv.l, jv.r)
          END AS val) v
    ),
    per_tech AS (
      SELECT t.id AS technique_id, t.code AS technique_code,
             COUNT(g.joint) AS req_count,
             BOOL_OR(g.status = 'RED') AS any_red,
             BOOL_OR(g.status = 'YELLOW') AS any_yellow,
             BOOL_OR(g.status = 'GREY') AS any_grey,
             COALESCE(BOOL_OR(g.unit_pending OR g.no_ref), false) AS any_no_ref,
             COALESCE(jsonb_agg(
               CASE WHEN g.joint IS NOT NULL THEN
                 jsonb_build_object('joint', g.joint, 'status', g.status)
                 || CASE WHEN g.slr_basis THEN jsonb_build_object('basis', 'slr_norm') ELSE '{}'::jsonb END
               END) FILTER (WHERE g.joint IS NOT NULL), '[]'::jsonb) AS joint_status,
             COALESCE(ARRAY_REMOVE(ARRAY_AGG(
               CASE WHEN g.status = 'GREY' AND g.unit_pending THEN g.joint || ':cm_requirement_pending'
                    WHEN g.status = 'GREY' AND g.no_ref THEN g.joint || ':no_reference_range'
                    WHEN g.status = 'GREY' AND g.slr_basis THEN g.joint || ':slr_not_rated'
                    WHEN g.status = 'GREY' THEN g.joint || ':not_measured(min ' || fmt_num(g.req) || ')'
                    WHEN g.slr_basis AND g.status <> 'GREEN' THEN g.joint || ':slr_norm'
                    WHEN g.status <> 'GREEN' THEN g.joint || ':' || fmt_num(g.val) || ' vs min ' || fmt_num(g.req)
               END), NULL), ARRAY[]::text[]) AS limiting
        FROM techniques t
        LEFT JOIN graded g ON g.technique_code = t.code
       WHERE t.sport = v_sport
       GROUP BY t.id, t.code
    ),
    classified AS (
      SELECT technique_id, technique_code, joint_status,
             CASE WHEN req_count = 0 THEN 'GREY'
                  WHEN any_red THEN 'RED'
                  WHEN any_grey AND c_grey_beats_yellow THEN 'GREY'
                  WHEN any_yellow THEN 'YELLOW'
                  WHEN any_grey THEN 'GREY'
                  ELSE 'GREEN' END AS tier,
             CASE WHEN req_count = 0 THEN 'no_rule'
                  WHEN any_red THEN NULL
                  WHEN any_grey AND (c_grey_beats_yellow OR NOT any_yellow) THEN CASE WHEN any_no_ref THEN 'no_reference_range' ELSE 'incomplete' END
                  ELSE NULL END AS status_reason,
             CASE WHEN req_count = 0 OR NOT (any_red OR any_yellow OR any_grey) THEN ARRAY[]::text[]
                  ELSE limiting END AS limiting_joints
        FROM per_tech
    )
    INSERT INTO technique_eligibility
      (user_id, athlete_id, assessment_id, technique_id, technique_code, sport, tier, limiting_joints, joint_status, status_reason, computed_at)
    SELECT
      p_user_id, v_assessment.athlete_id, v_assessment.id, c.technique_id, c.technique_code,
      v_sport, c.tier, c.limiting_joints, c.joint_status, c.status_reason, v_now
    FROM classified c
    ON CONFLICT (user_id, assessment_id, technique_id)
    DO UPDATE SET
      tier = EXCLUDED.tier,
      limiting_joints = EXCLUDED.limiting_joints,
      joint_status = EXCLUDED.joint_status,
      status_reason = EXCLUDED.status_reason,
      technique_code = EXCLUDED.technique_code,
      sport = EXCLUDED.sport,
      athlete_id = EXCLUDED.athlete_id,
      computed_at = EXCLUDED.computed_at;

    GET DIAGNOSTICS v_written = ROW_COUNT;
    v_result := v_result || jsonb_build_object(v_sport, v_written);
  END LOOP;

  RETURN jsonb_build_object(
    'user_id', p_user_id,
    'assessment_id', v_assessment.id,
    'status', 'ok',
    'written', v_result
  );
END;
$function$;
