-- ROMRxBJJ Exercise Library — 84 rows
-- Source: Google Sheet Exercise_Library tab

INSERT INTO public.exercises (joint_key, exercise_type, name, sets, reps, coaching_cue, video_url) VALUES
  ('hip_er', 'resistance', 'Clamshell with Band', 3, '15-20', 'Controls guard hook depth and seated guard mobility', NULL),
  ('hip_er', 'resistance', 'Seated Banded Hip External Rotation', 3, '10-12', 'Mimics seated guard ER demands for De La Riva and X-Guard', NULL),
  ('hip_er', 'resistance', 'Standing Hip CARs (Controlled Articular Rotations)', NULL, '3-5', 'Builds active hip control for scrambles and transitions', NULL),
  ('hip_er', 'stretch', 'Supine Figure-4 Stretch (Piriformis Stretch)', 3, '30-60', 'Releases muscles restricting guard hook depth', NULL),
  ('hip_er', 'stretch', '90/90 Hip External Rotation Stretch', NULL, '60-90', 'Directly transfers to guard retention and triangle setup', NULL),
  ('hip_er', 'foam_roll', 'Piriformis/Glute Foam Roll', NULL, '60-90', 'Reduces trigger points inhibiting glute function for guard work', NULL),
  ('hip_ir', 'resistance', 'Seated Banded Hip Internal Rotation', 3, '8-12', 'Builds active control for knee cut passes and guard retention', NULL),
  ('hip_ir', 'resistance', 'Quadruped Band-Assisted Hip IR Mobilization', NULL, '10', 'Combines mobility and strengthening for pass mechanics', NULL),
  ('hip_ir', 'resistance', '90/90 Transitions (Hip Switches)', NULL, NULL, 'Directly builds hip rotation symmetry for scrambles', NULL),
  ('hip_ir', 'stretch', '90/90 Internal Rotation Stretch', NULL, '30-60', 'Addresses posterior capsule restrictions limiting guard passes', NULL),
  ('hip_ir', 'stretch', 'Prone Hip Internal Rotation Stretch', NULL, '60', 'Gentle option for athletes with knee sensitivity from guard work', NULL),
  ('hip_ir', 'foam_roll', 'TFL/Lateral Hip Foam Roll', NULL, '60-90', 'Releases lateral hip restrictions that limit knee cut mechanics', NULL),
  ('hip_abduction', 'resistance', 'Side-Lying Hip Abduction with Band', 3, '15', 'Builds mount stability and open guard base', NULL),
  ('hip_abduction', 'resistance', 'Lateral Band Walks', 3, NULL, 'Transfers directly to wide base guard positions', NULL),
  ('hip_abduction', 'resistance', 'Kettlebell Goblet Squat (Wide Stance)', 3, '8-10', 'Strengthens deep squat for X-guard and spider guard entries', NULL),
  ('hip_abduction', 'stretch', 'Frog Stretch', 3, '45-60', 'Releases adductors restricting guard width and mount stability', NULL),
  ('hip_abduction', 'stretch', 'Standing Adductor Stretch (Side Lunge)', 3, '30', 'Functional stretch for wide-base passing positions', NULL),
  ('hip_abduction', 'foam_roll', 'Adductor (Inner Thigh) Foam Roll', NULL, '60-90', 'Improves groin mobility for open guard and mount transitions', NULL),
  ('hip_flexion', 'resistance', 'Goblet Squat with Pause', 3, '8', 'Builds deep flexion strength for closed guard and armbar setup', NULL),
  ('hip_flexion', 'resistance', '90/90 Hip Lift (Front Leg Focus)', 3, '8-10', 'Mimics closed guard mechanics with integrated hip flexion and ER', NULL),
  ('hip_flexion', 'resistance', 'Standing Knee Drive with Band', 3, '12-15', 'Directly transfers to shooting takedowns and guard pulls', NULL),
  ('hip_flexion', 'stretch', 'Kneeling Hip Flexor Stretch (Lunge Stretch)', 3, '30-60', 'Improves hip flexor length for guard retention and passing', NULL),
  ('hip_flexion', 'stretch', 'Supine Knee-to-Chest Stretch', NULL, '30-60', 'Identifies posterior hip capsule restrictions limiting guard depth', NULL),
  ('hip_flexion', 'foam_roll', 'Quadriceps/Rectus Femoris Foam Roll', NULL, '60-90', 'Addresses sitting-related tightness limiting guard performance', NULL),
  ('hip_extension', 'resistance', 'Glute Bridge with Hip Abduction', 3, '12-15', 'Superior glute activation for bridging escapes and tripod passing', NULL),
  ('hip_extension', 'resistance', 'Single Leg Romanian Deadlift with Kettlebell', 3, '8-10', 'Transfers directly to bridging and posting mechanics', NULL),
  ('hip_extension', 'resistance', 'Prone Hip Extension (Bird Dog Variation)', 3, '12-15', 'Builds hip extension strength without low back compensation', NULL),
  ('hip_extension', 'stretch', 'Kneeling Lunge with Posterior Pelvic Tilt', 3, '30-60', 'Improves hip flexor length for powerful bridging escapes', NULL),
  ('hip_extension', 'stretch', 'Couch Stretch (Rectus Femoris Emphasis)', NULL, '60', 'Addresses two-joint muscle restricting bridge power', NULL),
  ('hip_extension', 'foam_roll', 'Hip Flexor/Psoas Foam Roll', NULL, '60', 'Releases hip flexor tightness from prolonged sitting', NULL),
  ('shoulder_er', 'resistance', 'Side-Lying Shoulder External Rotation with Band', 3, '12-15', 'Builds rotator cuff strength for defending Americana and Kimura', NULL),
  ('shoulder_er', 'resistance', 'Band Face Pull with External Rotation', 3, '12-15', 'Trains posture and shoulder health for grip fighting', NULL),
  ('shoulder_er', 'resistance', 'Prone Y Raise', 3, '10-12', 'Essential for healthy overhead mechanics and ER positioning', NULL),
  ('shoulder_er', 'stretch', 'Doorway Pec Stretch', 5, '30', 'Restores shoulder alignment for submission defense', NULL),
  ('shoulder_er', 'stretch', 'Sleeper Stretch', 3, '30-45', 'Addresses posterior capsule tightness from grappling', NULL),
  ('shoulder_er', 'foam_roll', 'Posterior Shoulder/Infraspinatus Release with Ball', NULL, '60-90', 'Releases rotator cuff tension from repeated grappling exchanges', NULL),
  ('shoulder_flexion', 'resistance', 'Wall Slide (Forearm Version)', 3, '10-12', 'Builds healthy overhead movement for spider guard grips', NULL),
  ('shoulder_flexion', 'resistance', 'Prone Y Raise', 3, '10-12', 'Optimal lower trap activation for overhead sweep mechanics', NULL),
  ('shoulder_flexion', 'resistance', 'Kettlebell Arm Bar', 3, '20-30', 'Builds shoulder stability for frames and rear naked choke mechanics', NULL),
  ('shoulder_flexion', 'stretch', 'Child''s Pose Lat Stretch', NULL, '60-90', 'Releases lats restricting overhead frames and turtle escapes', NULL),
  ('shoulder_flexion', 'stretch', 'Supine Overhead Stretch with Band', 3, '30-45', 'Improves overhead mobility for spider guard and sweeps', NULL),
  ('shoulder_flexion', 'foam_roll', 'Lat Foam Roll', NULL, '60-90', 'Improves overhead mobility for spider guard and frames', NULL),
  ('lumbar_flexion', 'resistance', 'Cat-Cow (Spinal Flexion/Extension)', NULL, NULL, 'Improves segmental spinal mobility for guard retention and inverting', NULL),
  ('lumbar_flexion', 'resistance', 'Seated Jefferson Curl (Bodyweight)', 3, NULL, 'Builds spinal flexion tolerance for turtle and rolling positions', NULL),
  ('lumbar_flexion', 'resistance', 'Quadruped Rock Back', 3, '10-12', 'Safe spinal mobility exercise for guard and inversion prep', NULL),
  ('lumbar_flexion', 'stretch', 'Child''s Pose', NULL, '60-90', 'Restorative pose promoting lumbar flexion for guard play', NULL),
  ('lumbar_flexion', 'stretch', 'Supine Double Knee-to-Chest', NULL, '30-60', 'Opens posterior spine for guard retention and rolling mechanics', NULL),
  ('lumbar_flexion', 'foam_roll', 'Thoracic Spine Foam Roll (Extension)', NULL, '60-90', 'Reduces compensatory lumbar demand during guard play', NULL),
  ('lumbar_extension', 'resistance', 'McKenzie Press-Up (Prone Press-Up)', NULL, '10', 'Essential for posture in guard and bridging mechanics', NULL),
  ('lumbar_extension', 'resistance', 'Prone Sphinx Hold', NULL, NULL, 'Builds extension tolerance for posture in guard and sprawling', NULL),
  ('lumbar_extension', 'resistance', 'Glute Bridge (Single Leg)', 3, '10-12', 'Increases gluteus maximus demand for explosive bridge escapes', NULL),
  ('lumbar_extension', 'stretch', 'Kneeling Hip Flexor Stretch', 3, '30-60', 'Improves hip extension and reduces anterior pelvic tilt for posture', NULL),
  ('lumbar_extension', 'stretch', 'Standing Hip Flexor Stretch (Standing Lunge)', 2, '30', 'Standing hip flexor stretch for functional extension mobility', NULL),
  ('lumbar_extension', 'foam_roll', 'Thoracic Spine Extension over Foam Roller', NULL, '60-90', 'Reduces compensatory lumbar hyperextension during BJJ movements', NULL),
  ('ankle_df', 'resistance', 'Knee-to-Wall Mobilization', 3, '10-15', 'Builds stable base for guard play, takedowns, and kneeling positions', NULL),
  ('ankle_df', 'resistance', 'Seated Calf Raise (Soleus Focus)', 3, '12-15', 'Targets soleus restricting ankle mobility in squatting positions', NULL),
  ('ankle_df', 'resistance', 'Banded Ankle Dorsiflexion', 3, '10-15', 'Addresses joint and soft tissue restrictions for shooting takedowns', NULL),
  ('ankle_df', 'stretch', 'Standing Gastrocnemius Stretch (Straight Knee)', 3, '30-60', 'Targets gastroc restricting dorsiflexion in squat base', NULL),
  ('ankle_df', 'stretch', 'Bent-Knee Soleus Stretch', 3, '30-60', 'Isolates soleus for kneeling position comfort and takedown stability', NULL),
  ('ankle_df', 'foam_roll', 'Calf Foam Roll', NULL, '30-', 'Immediate ROM improvement for pre-training ankle mobility', NULL),
  ('cervical_flexion', 'resistance', 'Supine Chin Tuck with Head Lift', 3, '10', 'Retrains motor control for guard pulls and chin tuck protection', NULL),
  ('cervical_flexion', 'resistance', 'Isometric Neck Flexion (Hand Resistance)', 3, '10', 'Builds neck strength for overhead sweeps and triangle setup', NULL),
  ('cervical_flexion', 'resistance', 'Banded Neck Flexion', 3, '10-15', 'Progressive overload for neck injury prevention in BJJ', NULL),
  ('cervical_flexion', 'stretch', 'Suboccipital Stretch (Chin Tuck Overpressure)', 3, '30', 'Addresses muscles restricting flexion from screen time and guard play', NULL),
  ('cervical_flexion', 'stretch', 'Upper Trapezius Stretch', 5, '30', 'Releases trap tightness from guard work and defensive postures', NULL),
  ('cervical_flexion', 'foam_roll', 'Suboccipital Foam Roller Release', NULL, '60-90', 'Reduces tension headaches and improves flexion for guard positioning', NULL),
  ('cervical_extension', 'resistance', 'Prone Chin Tuck with Head Lift', 3, '10', 'Builds extension strength for takedown posture and guard top posture', NULL),
  ('cervical_extension', 'resistance', 'Quadruped Neck Retraction/Extension', 3, '10-12', 'Functional extensor control for posture in opponent''s guard', NULL),
  ('cervical_extension', 'resistance', 'Isometric Neck Extension (Hand Resistance)', 3, '10', 'Strengthens extensors for guillotine defense and visual contact from bottom', NULL),
  ('cervical_extension', 'stretch', 'SCM (Sternocleidomastoid) Stretch', 3, '30', 'Addresses forward head posture limiting takedown head-up position', NULL),
  ('cervical_extension', 'stretch', 'Anterior Scalene Stretch', 3, '20-30', 'Releases anterior neck restrictions for guillotine finish mechanics', NULL),
  ('cervical_extension', 'foam_roll', 'Thoracic Spine Extension (Supports Cervical Extension)', NULL, '60-90', 'Reduces cervical hyperextension demand during BJJ posture work', NULL),
  ('cervical_rotation', 'resistance', 'Supine Cervical Rotation with Chin Tuck', 3, '10-15', 'Builds rotation control for hip throws and tracking opponents', NULL),
  ('cervical_rotation', 'resistance', 'Isometric Neck Rotation (Hand Resistance)', 3, '10', 'Strengthens rotators for armbars, kimuras, and bow-and-arrow choke', NULL),
  ('cervical_rotation', 'resistance', 'Neck CARs (Controlled Articular Rotations)', NULL, '3-5', 'Essential for scramble awareness and tracking opponents in BJJ', NULL),
  ('cervical_rotation', 'stretch', 'Levator Scapulae Stretch', 3, '30-45', 'Releases restriction limiting rotation for throws and scramble awareness', NULL),
  ('cervical_rotation', 'stretch', 'SCM Rotation Stretch', 3, '30', 'Addresses rotational deficits from always looking same direction in guard', NULL),
  ('cervical_rotation', 'foam_roll', 'Posterior Cervical/Upper Trap Release', NULL, '60-90', 'Releases trigger points in upper trap restricting cervical rotation', NULL),
  ('cervical_lateral_flexion', 'resistance', 'Side-Lying Neck Lateral Flexion', 3, '10-15', 'Builds lateral neck strength for resisting crossface pressure', NULL),
  ('cervical_lateral_flexion', 'resistance', 'Isometric Lateral Neck Flexion (Hand Resistance)', 3, '10', 'Critical for resisting crossface pressure in passing', NULL),
  ('cervical_lateral_flexion', 'resistance', 'Banded Lateral Neck Flexion', 3, '10-15', 'Progressive neck strengthening for crossface defense and scarf hold', NULL),
  ('cervical_lateral_flexion', 'stretch', 'Scalene Stretch', 3, '20-30', 'Releases scalene tightness for balanced cervical lateral mobility', NULL),
  ('cervical_lateral_flexion', 'stretch', 'Lateral Neck Stretch (Ear to Shoulder)', 3, '30', 'Simple maintenance stretch for balanced cervical lateral ROM', NULL),
  ('cervical_lateral_flexion', 'foam_roll', 'Lateral Neck/Upper Trap Release', NULL, '60', 'Releases upper trap trigger points restricting lateral flexion', NULL);
